language: node_js
on:
  tags: false
os:
  - linux
  - osx
node_js:
  - node # latest node
  - 9
  - 8
  - 7
  - 6.14 # minimum
git:
  depth: 5
matrix:
  allow_failures:
    - node_js: node
  fast_finish: true
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH=$HOME/.yarn/bin:$PATH
script: echo "Running test against $(node -v) ..."  
after_success:

jobs:
  include:
    - stage: publish
      if: tag IS present AND repo =~ ^JimiC
      node_js: 6.14      
      deploy:
        provider: npm
        email: jimikar@gmail.com
        api_key: $NPM_TOKEN
        on:
          tags: true
