language: node_js
node_js: 
  - node
git:
  depth: 5
jobs:
  include:
    - stage: test
      if: NOT tag IS present
      script: echo "Running test against $(node -v) ..."  
    - stage: publish
      if: tag IS present AND repo =~ ^JimiC/npm-publish-testing
      node_js: node      
      deploy:
        provider: npm
        email: jimikar@gmail.com
        api_key: $NPM_TOKEN
