language: node_js
node_js:
  - node # latest node
  - 6.14 # minimum
os:
  - linux
  - osx
git:
  depth: 5
matrix:
  allow_failures:
    - node_js: node
  fast_finish: true
cache: yarn
before_install:
  - curl -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

jobs:
  include:
    - stage: publish
      if: tag IS present AND repo =~ ^JimiC
      os: linux
      node_js: 6.14
      script: npm run prepublishOnly
      deploy:
        skip_cleanup: true
        provider: npm
        email: jimikar@gmail.com
        api_key: $NPM_TOKEN
        on:
          tags: true
