name: Node CD

on:
  push:
    tags: '*'

jobs:
  publish:
    name: Publish

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_js:
          - 8 # minimum

    steps:
      - name: Cloning repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 5

      - name: "Setting up Node.js: ${{ matrix.node_js }}"
        uses: actions/setup-node@v1.1.2
        with:
          node-version: ${{ matrix.node_js }}

      - name: Build info
        run: |
          node --version
          npm --version

      - name: Installing dependencies
        run: npm ci

      - name: Publishing to NPM
        uses: actions/npm@v2.0.0
        env:
          # NPM_REGISTRY_URL: https://registry.npmjs.org
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          args: publish
